require 'squib'

verso = '../common/ajiro-back.pdf'

task default: [:deck]

directory "_verso"
directory "_publish"

task :deck do
  load 'deck.rb'
end

task :verso => [:deck, "_verso"] do
  Dir["_output/*.pdf"].each do |pdf|
    pages = `pdfinfo #{pdf} | awk '/Pages:/ {print $2}'`.to_i
    name = File.basename(pdf, '.pdf')
    shuffle = (1..pages).map {|i| "A#{i} B1"}.join(" ")
    sh "pdftk A=#{pdf} B=#{verso} cat #{shuffle} output _verso/#{name}.pdf"
  end
end

task :publish => [:verso, "_publish"] do
  parts = Dir["_verso/*.pdf"]
  sh "pdftk #{parts.join(" ")} cat output _publish/cards.pdf"
end
